# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 036812f3f0040971e36edc101d4eb9e9d4b948372a71f6786666c55e27f67668e6f456fdb702e9751b474edcee9325b8a0acad6c02bac447faf6bf01535dd169

test:
  secret_key_base: 5a40284c25f2ea9daf9a783e96dcf3606e915df7ad53481b0b4862c460a8f6cbfd6bdd6ac36ebf7426d0a26f72bcb55fe4236308dfb30c6352db8c306c3a7c7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
